services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: retail_pricing
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retailadmin@123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: