"""add pricing and upload tables

Revision ID: 5f434927af54
Revises: eb9a4ceaf9ad
Create Date: 2026-07-16 14:07:27.788374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f434927af54'
down_revision: Union[str, Sequence[str], None] = 'eb9a4ceaf9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pricing_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', 'pricing_date', name='uq_pricing_store_sku_date')
    )
    op.create_index(op.f('ix_pricing_records_pricing_date'), 'pricing_records', ['pricing_date'], unique=False)
    op.create_index(op.f('ix_pricing_records_product_name'), 'pricing_records', ['product_name'], unique=False)
    op.create_index(op.f('ix_pricing_records_sku'), 'pricing_records', ['sku'], unique=False)
    op.create_index(op.f('ix_pricing_records_store_id'), 'pricing_records', ['store_id'], unique=False)
    op.create_table('pricing_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_uploads')
    op.drop_index(op.f('ix_pricing_records_store_id'), table_name='pricing_records')
    op.drop_index(op.f('ix_pricing_records_sku'), table_name='pricing_records')
    op.drop_index(op.f('ix_pricing_records_product_name'), table_name='pricing_records')
    op.drop_index(op.f('ix_pricing_records_pricing_date'), table_name='pricing_records')
    op.drop_table('pricing_records')
    # ### end Alembic commands ###
